In [1]:
# Imports
import torch

In [7]:
# Create a tensor
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [8]:
# Define a function
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [11]:
# Back prop
y.backward() # backpropagation

In [13]:
# Display the resultant gradient
x.grad   # first derivate of y when we plug in x value

tensor(93.)

### Back-propagation on multiple steps

In [14]:
# Create a tensor
x = torch.tensor([[1., 2, 3],[3, 2, 1]], requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [15]:
# Create the first layer with y = 3*x + 2
y = 3*x + 2
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [16]:
# Create the second layer
z = 2*y**2
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [17]:
# set the output to the matrix mean
out = z.mean()
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [18]:
# Now perform back-propagation to find the gradient of x w.r.to out
out.backward()
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])


### Trun off tracking

Set requires_grad = False as needed in tensor

When performing evaluations, it's often helpful to wrap a set of operations in with `torch.no_grad():`

A less-used method is to run `.detach()` on a tensor to prevent future computations from being tracked. This can be handy when cloning a tensor.