# Tensor Basics

Reference: Krish Naik's Pytorch playlist from Youtube: https://www.youtube.com/watch?v=3XA4ojhq44Q

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [3]:
import torch

In [4]:
torch.__version__

'1.5.1'

In [8]:
import numpy as np
lst = [1,2,5]
arr = np.array(lst) # converting the list to numpy array
arr.dtype

dtype('int64')

### Convert Numpy array to Pytorch Tensors

In [9]:
tensor = torch.from_numpy(arr)
tensor

tensor([1, 2, 5])

NOTE: The returned tensor and :attr:`ndarray` share the same memory. Modifications to
the tensor will be reflected in the :attr:`ndarray` and vice versa. The returned
tensor is not resizable.

This is the disadvantage of from_numpy. Solution can be found below.

In [11]:
tensor.dtype

torch.int64

In [12]:
tensor[0] = -1
tensor

tensor([-1,  2,  5])

In [13]:
arr

array([-1,  2,  5])

In [17]:
# Indexing similar to numpy
tensor[:2]

tensor([-1,  2])

In [18]:
# Prevent tensor and numpy array using same memory location using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([-1,  2,  5])

In [19]:
tensor_arr.dtype

torch.int64

In [20]:
tensor_arr[0] = 10
tensor_arr

tensor([10,  2,  5])

In [21]:
arr

array([-1,  2,  5])

Observe that tensor_arr and arr are different now.

In [22]:
# Zeros and ones
torch.zeros(2,3, dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [24]:
torch.ones(3,2, dtype=torch.int64)

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [29]:
a = torch.tensor(np.arange(0,15).reshape(3,5))
a

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [33]:
a[:,:2]

tensor([[ 0,  1],
        [ 5,  6],
        [10, 11]])

### Arithmetic Operation

In [37]:
a = torch.tensor([1,2,3], dtype = torch.float)
b = torch.tensor([4,5,6], dtype = torch.float)
c = a + b
print(c)

tensor([5., 7., 9.])


In [38]:
a.shape

torch.Size([3])

In [28]:
c = torch.add(a,b)
c

tensor([5., 7., 9.])

In [35]:
d = torch.ones(3)
c + d

tensor([ 6.,  8., 10.])

In [42]:
# Another way to store result in variable
c = torch.zeros(3)
torch.add(a, b, out = c).sum() # sum of all values in c


tensor(21.)

In [43]:
print(c)

tensor([5., 7., 9.])


### Dot Products and Multiplication operations

In [44]:
x = torch.tensor([3,4,5], dtype = torch.float)
y = torch.tensor([5,6,7], dtype = torch.float)


In [45]:
x.mul(y)

tensor([15., 24., 35.])

In [46]:
x.dot(y) #3*5 + 4*6 + 5*7

tensor(74.)

In [47]:
3*5 + 4*6 + 5*7

74

In [49]:
# Matrix multiplication
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[2,3],[5,6],[9,8]], dtype = torch.float)
torch.matmul(x,y)

tensor([[40., 43.],
        [72., 73.]])

In [50]:
torch.mm(x,y)

tensor([[40., 43.],
        [72., 73.]])

In [51]:
x@y

tensor([[40., 43.],
        [72., 73.]])

matmul, mm, @ are are all same - used for matrix multiplication