In [1]:
import torch
print(torch.cuda.is_available())

True


In [2]:
print(torch.rand(2,2))

tensor([[0.6490, 0.6920],
        [0.0280, 0.3389]])


In [4]:
x = torch.tensor([[0,0,1], [1,1,1], [0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [5]:
# change x
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [6]:
# Zeros
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [8]:
torch.ones(1,2) + torch.ones(1,2)

tensor([[2., 2.]])

In [9]:
# copying the tensors
cpu_tensor = torch.rand(2)
cpu_tensor

tensor([0.0857, 0.6293])

In [10]:
cpu_tensor.device

device(type='cpu')

In [11]:
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

device(type='cuda', index=0)

In [16]:
# Find the maximum item
print(torch.rand(2,2).max())
print(torch.rand(2,2).max().item())

tensor(0.6993)
0.7638583183288574


In [17]:
# Changing the type of tensors
long_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [18]:
float_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]]).to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

In [19]:
# Reshaping tensor
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1,28,28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [20]:
reshaped_tensor = flat_tensor.reshape(1,28,28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

The difference is between view() and reshape(). The answer is that view() operates as a view on the original tensor, so if the underlying data is changed, the view will change too (and vice versa). However, view() can throw errors if the required view is not contiguous; that is, it doesn’t share the same block of memory it would occupy if a new tensor of the required shape was created from scratch. If this happens, you have to call tensor.contiguous() before you can use view(). However, reshape() does all that behind the scenes, so in general, it is recommended using reshape() rather than view().

In [22]:
# Rearrange the dimensions
hwc_tensor = torch.rand(640, 480, 3) # height, width, channel
chw_tensor = hwc_tensor.permute(2,0,1) # channel, height, width
chw_tensor.shape

torch.Size([3, 640, 480])